### ISSUE TITLE
Unhandled Promise Rejection - Relayer

### ISSUE THREAD

**Issue by tkporter** [celo-org/komenci#109]
Seeing unhandled promise rejection logs on the relayer. The rejection should be caught and logged appropriately in JSON (at least when `NODE_ENV=production`)

```
$ kubectl logs komenci-relayer-0 -n komenci
...
...
{"level":30,"time":1604519480419,"pid":56,"hostname":"komenci-relayer-0","message":"Transaction Submitted","destination":"0xFd986A1Fb25E5eAB006435617271fA22Fa659F53","data":"0xea36cbc5000000000000000000000000ad5e5722427d79dff28a4ab30249729d1f8b4cc0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000001ca81adde30075ca5e43e0fbc24792352c03b237cb8ff122ebe6bc5759cef35c46329acfc00a474728fdccdd4e65d0dd656f728c2ebb62f4eaa424448455717a220000000000000000000000000000000000000000000000000000000000000024e221932e73e4171139bc76d653fd22bb7d2e0865395bf9c63b6ecd2a9ff8020ab3d3359a00000000000000000000000000000000000000000000000000000000","value":"0x0","hash":"0x4eedfcdf42909ca2c18f754a034880908608bb6cf5c6101111f354e1e921bc7b"}
(node:56) UnhandledPromiseRejectionWarning: Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0x95a604a6bef978c9c4faf060694ca09a245cf2163346e99f1b861cc282201888",
  "blockNumber": 1855429,
  "contractAddress": null,
  "cumulativeGasUsed": 212112,
  "from": "0xa7d74cb4fca9458757cfc8b90d9b38a126f68b47",
  "gasUsed": 212112,
  "logs": [],
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0xfd986a1fb25e5eab006435617271fa22fa659f53",
  "transactionHash": "0x4eedfcdf42909ca2c18f754a034880908608bb6cf5c6101111f354e1e921bc7b",
  "transactionIndex": 0
}
    at /app/node_modules/web3-eth/node_modules/web3-core-method/src/index.js:412:37
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:56) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 131)
```

**Comment by bowd** [comment]
This was solved. It had to do with our TransactionResult object where if you had to explicitly consume the receipt promise.
